clean:
	find . -name *.pyc -exec rm -v {} \;
	find . -name __pycache__ -exec rm -rfv {} \;

scss:
	scss resources/scss/src:resources/scss/cc

scss_live:
	scss --watch resources/scss/src:resources/scss/cc